### ISSUE TITLE
Valuelist-choose-delimiter

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/honey-badger#9]
Can we add a function to choose the delimiter? I actually would like to use semicolon, because I have commas in my strings :)
E.g. "5.3 Verkauf Möbel, Bau, Garten"

**Comment by daren-thomas** [comment]
@christophwaibel you can also just wrap values in double quotes, so a line could read:

```
1, "5.3 Verkauf Möbel, Bau, Garten", next field, 0.72, 42
```

Can you try that? It should just work. Also, since we use the `csv` module to read the csv files and that tries to auto-detect the dialect used, you can just use semi-colons. Try it, it should just work.

Editing CSV files works rather well with Excel - I'd be surprised if Excel output isn't read correctly by the `csv` module.

**Comment by daren-thomas** [comment]
closing, as I don't believe we should do it that way. instead, use double quotes to wrap fields with commas. delimiter is not specifically specified in honey-badger, so it uses the default algorithm of the `csv` module to figure it out. use `,`. use Excel to save the file and allow quoting of field values.
